# Generated by Django 4.2.4 on 2023-10-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='property_id',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
