# Generated by Django 4.2.4 on 2023-10-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('luxury', 'Luxury Estate'), ('oceanfront', 'Oceanfront Retreats'), ('urban', 'Urban Living Gems'), ('countryside', 'Countryside Escapes')], default='luxury', max_length=20),
        ),
    ]
