# Generated by Django 4.2.4 on 2023-10-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_images',
        ),
    ]
